### ISSUE TITLE
Deaths are counted but not shown on screen

### ISSUE THREAD

**Issue by justiziabelle** [jogeuncheol/Death_Counter#5]
The app opens and it counts my deaths but there is no message on screen like in the gifs. i'm playing borderless windowed and i'm using ModEngine. Could that be the problem?

**Comment by jogeuncheol** [comment]
oh, the message on screen is not a function of this programs.
I'm sorry It is a function of an obs or similar broadcast program.
the gif's was recorded with the function of displaying the text of the broadcast program on the screen.
I'm sorry to confuse you.
And thank you for using it.
